apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogae-deployed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      serviceAccountName: kubernetes-ksa
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/xenon-petal-407313/clouddemo/kogae_deployment_image:v1.0
        env:
          - name: DB_USER
            value: Austin
          - name: DB_PASS
            value: November@06
          - name: DB_NAME
            value: production-kogae
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "256Mi"
            cpu: "0.25"
        ports:
        - containerPort: 80

      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2
        args: 
          - "--structured-logs"
          - "--port=5432"
          - "xenon-petal-407313:us-central1:postgresql-database-new"
        securityContext: 
          runAsNonRoot: true
        volumeMounts:
          - name: postgresql-storage
            mountPath: /var/lib/postgresql/data
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
          requests:
            memory: "2Gi"
            cpu: "1"
      volumes:
        - name: postgresql-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kogae-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
