apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogae-deployed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
    containers:
    - name: backend-app
      image: us-central1-docker.pkg.dev/xenon-petal-407313/clouddemo/kogae_deployment_image:v1.0
    ports:
            - containerPort: 80

          

---
apiVersion: v1
kind: Service
metadata:
  name: kogae-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

    
