apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogae-deployed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/xenon-petal-407313/clouddemo/kogae_deployment_image:v1.0
        resources:
          limits:
            memory: "512Mi"
            cpu: "0.5"
          requests:
            memory: "256Mi"
            cpu: "0.25"
        ports:
        - containerPort: 80

      - name: postgresql
        image: postgres:latest
        env:
          - name: POSTGRES_DB
            value: production-kogae
          - name: POSTGRES_USER
            value: Austin
          - name: POSTGRES_PASSWORD
            value: November@06
        ports:
          - containerPort:5432 
        resources:
          limits:
            memory: "256Mi"
            cpu: "0.1"
          requests:
            memory: "128Mi"
            cpu: "0.05"

---
apiVersion: v1
kind: Service
metadata:
  name: kogae-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
