apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogae-deployed-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 120
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/kogae-minet/kogae-repository/kogae_deployment_image:v1.0
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kogae-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80