apiVersion: apps/v1
kind: Deployment
metadata:
  name: kogae-deployed-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 120
  template:
    metadata:
      labels:
        app: backend-app
    spec:
      serviceAccountName: kubernetes-ksa
      containers:
      - name: backend-app
        image: us-central1-docker.pkg.dev/xenon-petal-407313/clouddemo/kogae_deployment_image:v1.0
        env:
          - name: DB_USER
            value: Austin
          - name: DB_PASS
            value: November@06
          - name: DB_NAME
            value: production-kogae
          - name: DB_HOST
            value: 104.197.117.79
          - name: DB_ENGINE
            value: django.db.backends.postgresql
        ports:
        - containerPort: 80

      - name: cloud-sql-proxy
        image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.8.2
        args: 
          - "--structured-logs"
          - "--port=5432"
          - "xenon-petal-407313:us-central1:postgresql-database-new"
        securityContext: 
          runAsNonRoot: true
        volumeMounts:
          - name: postgresql-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgresql-storage
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: kogae-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: backend-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080