# Generated by Django 3.0.5 on 2023-11-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0005_custommodelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='policy_name',
            field=models.CharField(max_length=205),
        ),
    ]
