# Generated by Django 3.0.5 on 2023-11-22 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_auto_20231122_1541'),
        ('insurance', '0006_auto_20231121_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='insured',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='customer.Customer', to_field='id_number'),
        ),
    ]
