# Generated by Django 3.0.5 on 2023-11-23 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0007_policy_insured'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='cover_end',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='policy',
            name='cover_start',
            field=models.DateField(null=True),
        ),
    ]
