# Generated by Django 3.0.5 on 2023-11-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0008_auto_20231123_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='policy_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
