# Generated by Django 5.0 on 2024-02-16 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0027_alter_thirdpartycarinsurance_blue_book"),
        ("insurance", "0009_policy_policy_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="expiry_date",
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name="ThirdpartyPolicy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("policy_name", models.CharField(max_length=205)),
                ("sum_assurance", models.PositiveIntegerField()),
                ("premium", models.PositiveIntegerField()),
                ("tenure", models.PositiveIntegerField()),
                ("creation_date", models.DateField(auto_now=True)),
                ("cover_start", models.DateField(null=True)),
                ("cover_end", models.DateField(null=True)),
                (
                    "policy_number",
                    models.CharField(blank=True, max_length=20, null=True, unique=True),
                ),
                ("expiry_date", models.DateField(null=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insurance.category",
                    ),
                ),
                (
                    "insured",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thirdparty_policies",
                        to="customer.customer",
                        to_field="id_number",
                    ),
                ),
            ],
        ),
    ]
