# Generated by Django 5.0 on 2024-02-20 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0013_thirdpartypolicyrecord"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thirdpartypolicyrecord",
            name="Policy",
        ),
        migrations.AddField(
            model_name="thirdpartypolicyrecord",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="insurance.thirdpartypolicy",
            ),
        ),
    ]
