# Generated by Django 5.0 on 2024-02-20 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0014_remove_thirdpartypolicyrecord_policy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thirdpartypolicy",
            name="premium",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
