# Generated by Django 5.0 on 2024-02-20 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0015_alter_thirdpartypolicy_premium"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ThirdpartyPolicyRecord",
        ),
    ]
