# Generated by Django 5.0 on 2024-02-20 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0017_thirdpartypolicyrecord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=21),
        ),
        migrations.AlterField(
            model_name="policy",
            name="policy_number",
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="policyrecord",
            name="status",
            field=models.CharField(default="Pending", max_length=101),
        ),
        migrations.AlterField(
            model_name="thirdpartypolicy",
            name="policy_number",
            field=models.CharField(blank=True, max_length=21, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="thirdpartypolicyrecord",
            name="status",
            field=models.CharField(default="Pending", max_length=101),
        ),
    ]
