# Generated by Django 5.0 on 2024-02-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0018_alter_category_category_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="thirdpartypolicyrecord",
            old_name="creation_date",
            new_name="thirdpartycreation_date",
        ),
        migrations.RenameField(
            model_name="thirdpartypolicyrecord",
            old_name="customer",
            new_name="thirdpartycustomer",
        ),
        migrations.RenameField(
            model_name="thirdpartypolicyrecord",
            old_name="policy",
            new_name="thirdpartypolicy",
        ),
        migrations.RenameField(
            model_name="thirdpartypolicyrecord",
            old_name="status",
            new_name="thirdpartystatus",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=2),
        ),
    ]
