# Generated by Django 5.0 on 2024-02-26 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "insurance",
            "0019_rename_creation_date_thirdpartypolicyrecord_thirdpartycreation_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(max_length=20),
        ),
    ]
