# Generated by Django 4.2.7 on 2025-10-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0020_alter_category_category_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name_plural": "Policies"},
        ),
        migrations.AlterModelOptions(
            name="thirdpartypolicy",
            options={"verbose_name_plural": "Thirdparty Policies"},
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="chassis_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle chassis/VIN number",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="engine_number",
            field=models.CharField(
                blank=True, help_text="Engine serial number", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="registration_number",
            field=models.CharField(
                blank=True,
                help_text="Vehicle registration number",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="territorial_limits",
            field=models.TextField(
                blank=True, help_text="Geographic coverage limits", null=True
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="vehicle_make",
            field=models.CharField(
                blank=True,
                help_text="Vehicle manufacturer (e.g., Toyota, BMW)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="vehicle_model",
            field=models.CharField(
                blank=True,
                help_text="Vehicle model (e.g., Camry, X5)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="vehicle_type",
            field=models.CharField(
                blank=True,
                help_text="Type of vehicle (e.g., Sedan, SUV, Hatchback)",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="thirdpartypolicy",
            name="vehicle_year",
            field=models.PositiveIntegerField(
                blank=True, help_text="Year of manufacture", null=True
            ),
        ),
    ]
