# Generated by Django 4.2.7 on 2025-10-24 10:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0021_alter_category_options_alter_policy_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="policy",
            name="district",
            field=models.CharField(
                blank=True,
                help_text="The administrative district",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="financial_interest",
            field=models.TextField(
                blank=True,
                help_text="Describe any financial interests, mortgages, or co-ownership details",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="plot_number",
            field=models.CharField(
                blank=True,
                help_text="The official plot number of the property",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="title_deed",
            field=models.FileField(
                blank=True,
                help_text="Upload property title deed (optional)",
                null=True,
                upload_to="homeowners/title_deeds/",
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="village",
            field=models.CharField(
                blank=True,
                help_text="The village or township name",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="policy",
            name="ward_kgotla",
            field=models.CharField(
                blank=True,
                help_text="The ward number or traditional authority (Kgotla) area",
                max_length=50,
                null=True,
            ),
        ),
    ]
