# Generated by Django 4.2.7 on 2025-10-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0022_policy_district_policy_financial_interest_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="policyrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=101,
            ),
        ),
        migrations.AlterField(
            model_name="thirdpartypolicyrecord",
            name="thirdpartystatus",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Active", "Active"),
                    ("Approved", "Approved"),
                    ("Rejected", "Rejected"),
                    ("Expired", "Expired"),
                ],
                default="Pending",
                max_length=101,
            ),
        ),
    ]
