# Generated by Django 4.2.7 on 2025-10-27 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurance", "0023_alter_policyrecord_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PolicyWording",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(help_text="Policy wording title", max_length=200),
                ),
                (
                    "policy_type",
                    models.CharField(
                        choices=[
                            ("Homeowners", "Homeowners Insurance"),
                            ("Motor", "Motor Insurance"),
                            ("General", "General Policy"),
                        ],
                        help_text="Type of policy",
                        max_length=50,
                    ),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version number (e.g., 1.0, 2.1)", max_length=20
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Brief description of the policy wording"
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        help_text="Upload policy wording document (PDF)",
                        upload_to="policy_wordings/",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Is this version currently active?"
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        help_text="Date when this version becomes effective"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_wordings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Policy Wordings",
                "ordering": ["-effective_date", "-version"],
                "unique_together": {("title", "version")},
            },
        ),
    ]
