# Generated by Django 4.2.7 on 2025-10-27 15:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("insurance", "0024_policywording"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answered_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answered_questions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answered_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
