# Generated by Django 5.0.6 on 2026-04-28 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0025_question_answered_by_question_answered_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "employee_id",
                    models.CharField(blank=True, max_length=20, unique=True),
                ),
                (
                    "department",
                    models.CharField(
                        choices=[
                            ("Claims", "Claims"),
                            ("Underwriting", "Underwriting"),
                            ("Finance", "Finance"),
                            ("IT", "IT"),
                            ("HR", "HR"),
                            ("Operations", "Operations"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Officer", "Officer"),
                            ("Analyst", "Analyst"),
                            ("Administrator", "Administrator"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
