# Generated by Django 5.0.6 on 2026-04-28 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0026_staffprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="PremiumRate",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.13,
                        help_text="Premium rate as a decimal (e.g. 0.13 = 13%). Annual Premium is calculated as Sum Insured × this rate.",
                        max_digits=6,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homeowners Premium Rate",
                "verbose_name_plural": "Homeowners Premium Rate",
            },
        ),
    ]
