# Generated by Django 3.0.5 on 2023-11-15 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_category_policy_policyrecord_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='category',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='policyrecord',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='question',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Policy',
        ),
        migrations.DeleteModel(
            name='PolicyRecord',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
