# Generated by Django 3.0.5 on 2023-11-22 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_auto_20231121_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
