# Generated by Django 3.0.5 on 2023-11-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_auto_20231127_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_type',
            field=models.CharField(blank=True, choices=[('ID', 'ID'), ('Passport', 'Passport')], max_length=10, null=True),
        ),
    ]
