# Generated by Django 3.0.5 on 2023-12-05 09:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_directdebitform_homeownerscover_kycform_thirdpartycarinsurance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitform',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='Forms/DirectDebit/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='homeownerscover',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='Forms/HomeOwnersCover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='kycform',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='Forms/KYC/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='thirdpartycarinsurance',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='Forms/ThirdPartyCarInsurance/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
