# Generated by Django 3.0.5 on 2023-12-07 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0011_auto_20231206_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kycform',
            old_name='file_upload',
            new_name='kyc_form',
        ),
        migrations.AlterField(
            model_name='kycform',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_form', to='customer.Customer'),
        ),
    ]
