# Generated by Django 3.0.5 on 2023-12-07 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_auto_20231207_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycform',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_form', to='customer.Customer', unique=True),
        ),
    ]
