# Generated by Django 3.0.5 on 2023-12-08 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_auto_20231207_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thirdpartycarinsurance',
            name='file_upload',
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='blue_book',
            field=models.FileField(blank=True, null=True, upload_to='Forms/ThirdPartyCarCover/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='car_type',
            field=models.CharField(choices=[('', 'Select car type'), ('Local', 'Local'), ('Import', 'Import')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='make',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='model',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='registered_owner',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='relationship_to_owner',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='thirdpartycarinsurance',
            name='year_of_manufacture',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='thirdpartycarinsurance',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thirdparty_car_cover', to='customer.Customer', unique=True),
        ),
    ]
