# Generated by Django 5.0 on 2023-12-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_alter_customer_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='profile_pic',
        ),
    ]
