# Generated by Django 5.0 on 2024-01-08 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_kycform_copy_of_omang_kycform_proof_of_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycform',
            name='copy_of_omang',
        ),
        migrations.RemoveField(
            model_name='kycform',
            name='proof_of_income',
        ),
        migrations.RemoveField(
            model_name='kycform',
            name='proof_of_residence',
        ),
    ]
