# Generated by Django 5.0 on 2024-01-09 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_kycform_copy_of_omang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycform',
            name='certified_copy_of_identity_card',
            field=models.FileField(blank=True, null=True, upload_to='Forms/CertifiedCopy/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='kycform',
            name='proof_of_income',
            field=models.FileField(blank=True, null=True, upload_to='Forms/ProofOfIncome/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AddField(
            model_name='kycform',
            name='proof_of_residence',
            field=models.FileField(blank=True, null=True, upload_to='Forms/ProofOfResidence/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
