# Generated by Django 5.0 on 2024-01-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_kycform_certified_copy_of_identity_card_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycform',
            name='certified_copy_of_identity_card',
        ),
        migrations.RemoveField(
            model_name='kycform',
            name='proof_of_income',
        ),
        migrations.RemoveField(
            model_name='kycform',
            name='proof_of_residence',
        ),
    ]
