# Generated by Django 5.0 on 2024-01-09 11:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_remove_kycform_certified_copy_of_identity_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyOfOmang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy_of_omang', models.FileField(blank=True, null=True, upload_to='Forms/CopyOfOmang/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copy_of_omang', to='customer.customer', unique=True)),
            ],
        ),
    ]
