# Generated by Django 5.0 on 2024-01-09 14:59

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_residenceproof'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeProof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_proof', models.FileField(blank=True, null=True, upload_to='Forms/IncomeProof/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_proof', to='customer.customer', unique=True)),
            ],
        ),
    ]
