# Generated by Django 5.0 on 2024-01-12 11:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0026_alter_homeownerscover_title_deed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thirdpartycarinsurance',
            name='blue_book',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
    ]
