# Generated by Django 4.2.7 on 2025-10-24 10:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0027_alter_thirdpartycarinsurance_blue_book"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="kycform",
            options={"verbose_name_plural": "KYC Forms"},
        ),
    ]
