# Generated by Django 4.2.7 on 2025-10-27 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0028_alter_kycform_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="kyc_approval_date",
            field=models.DateTimeField(
                blank=True, help_text="Date when KYC was approved", null=True
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kyc_expiry_date",
            field=models.DateField(
                blank=True,
                help_text="Date when KYC expires (typically 1-2 years from approval)",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kyc_last_updated",
            field=models.DateTimeField(
                auto_now=True, help_text="Last time KYC status was updated"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kyc_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about KYC status, reasons for rejection, etc.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kyc_reviewed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Admin who reviewed the KYC",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="kyc_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="kyc_status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Compliant", "Compliant"),
                    ("Non-Compliant", "Non-Compliant"),
                    ("Renewal Required", "Renewal Required"),
                ],
                default="Pending",
                help_text="Current KYC compliance status",
                max_length=20,
            ),
        ),
    ]
